# Generated by Django 5.1.4 on 2026-09-27 11:05

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.deletion
import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        # ExclusionConstraint'da integer (provider_id) ni '=' bilan solishtirish uchun kerak
        BtreeGistExtension(),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to="catalog.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "start_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_at__lt", models.F("end_at"))),
                        name="timeoff_start_before_end",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (scheduling.models.TsTzRange("start_at", "end_at"), "&&"),
                            ("provider", "="),
                        ],
                        name="timeoff_no_overlap",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="catalog.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["provider", "weekday"],
                        name="scheduling__provide_565c18_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="wh_start_before_end",
                    )
                ],
            },
        ),
    ]
