# Generated by Django 5.1.4 on 2026-09-29 07:14

import django.contrib.postgres.constraints
import django.db.models.deletion
import scheduling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("scheduling", "0001_initial"),   # btree_gist kengaytmasi shu migratsiyada o'rnatiladi
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "start_at"],
                        name="bookings_bo_provide_3bbc05_idx",
                    ),
                    models.Index(
                        fields=["customer", "start_at"],
                        name="bookings_bo_custome_68f0f9_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_at__lt", models.F("end_at"))),
                        name="booking_start_before_end",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        expressions=[
                            (scheduling.models.TsTzRange("start_at", "end_at"), "&&"),
                            ("provider", "="),
                        ],
                        name="booking_no_provider_overlap",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        expressions=[
                            (scheduling.models.TsTzRange("start_at", "end_at"), "&&"),
                            ("customer", "="),
                        ],
                        name="booking_no_customer_overlap",
                    ),
                ],
            },
        ),
    ]
